const router = require('express').Router()
const customerAuthController = require('../../controllers/home/customerAuthController')
router.post('/customer/customer-register', customerAuthController.customer_register)
router.post('/customer/customer-login', customerAuthController.customer_login)
router.get('/auth/verify-email', customerAuthController.verify_email)
router.post('/auth/resend-verification', customerAuthController.resend_verification)
router.post('/auth/forgot-password', customerAuthController.forgot_password)
router.post('/auth/reset-password', customerAuthController.reset_password)
router.post('/auth/refresh-token', customerAuthController.refresh_token)
router.post('/auth/logout', customerAuthController.customer_logout)
router.get('/customer/logout', customerAuthController.customer_logout)
module.exports = router
